[workloads]
search_path = "workloads/src"
tests = [
  "toy-toy-ctest-mvin_mvout_test-linux",
  "toy-toy-ctest-mvin_mvout_stride_test-linux",
  "toy-toy-ctest-bdb_counter_test-linux",
  "toy-toy-ctest-gemmini_os_cisc_basic_test-linux",
  "toy-toy-ctest-gemmini_os_cisc_atranspose_test-linux",
  "toy-toy-ctest-gemmini_os_cisc_btranspose_test-linux",
  "toy-toy-ctest-gemmini_os_cisc_shift_test-linux",
  "toy-toy-ctest-gemmini_os_risc_atranspose_test-linux",
  "toy-toy-ctest-gemmini_os_risc_btranspose_test-linux",
  "toy-toy-ctest-gemmini_os_risc_abtranspose_test-linux",
  "toy-toy-ctest-gemmini_os_risc_shift_test-linux",
  "toy-toy-ctest-gemmini_ws_cisc_conv_test-linux",
  "toy-toy-ctest-gemmini_ws_risc_basic_test-linux",
  "toy-toy-ctest-mmio_minimal_test-linux",
  "toy-toy-ctest-mxfp2int_test-linux",
]
