# Goban Rocket-only core configuration

memdomain = "memdomains/default.toml"

[rocketCore]
xLen = 64
pgLevels = 3
useVM = true
useZba = true
useZbb = true
useZbs = true
haveCFlush = false

[rocketCore.mulDiv]
enable = true
mulUnroll = 8
mulEarlyOut = true
divEarlyOut = true

[rocketCore.fpu]
enable = true
minFLen = 16
fLen = 64

[rocketCore.dcache]
nSets = 32
nWays = 4
nMSHRs = 4

[rocketCore.icache]
nSets = 64
nWays = 8

[rocketCore.btb]
enable = true
nEntries = 28
nRAS = 6
