# Pebble core memory domain configuration

[bank]
num = 24
width = 128
entries = 64
maskLen = 16
channel = 13

[dma]
nXacts = 8
burstMaxBytes = 1024
busWidth = 128
maxInFlightMemReqs = 16

[tlb]
size = 4

[tma]
readChannel = 4
writeChannel = 4

[mmio]
enable = false
bankNum = 5
bankEntries = 1024
bankWidth = 8
readWidth = 8

[mem]
addrLen = 39
