[workloads]
search_path = "workloads/src"
tests = [
  "pebble-pebble-ctest-mvin_mvout_test-linux",
  "pebble-pebble-ctest-mvin_mvout_stride_test-linux",
  "pebble-pebble-mlirtest-base_mvin_mvout_16x16_i8-linux",
  "pebble-pebble-mlirtest-base_bank_mvin_mvout_16x16_i8-linux",
  "pebble-pebble-ctest-transpose_i8_16x16_test-linux",
  "pebble-pebble-ctest-transpose_i8_16x32_test-linux",
  "pebble-pebble-ctest-transpose_i32_8x16_test-linux",
  "pebble-pebble-mlirtest-ball_transpose_16x16_i8-linux",
  "pebble-pebble-mlirtest-bank_transpose_16x16_i8-linux",
  "pebble-pebble-ctest-smatmul_bias_accumulate_test-linux",
  "pebble-pebble-ctest-smatmul_single_block_test-linux",
  "pebble-pebble-mlirtest-ball_smatmul_bias_accumulate-linux",
  "pebble-pebble-mlirtest-bank_smatmul_bias_accumulate-linux",
  "pebble-pebble-ctest-quant_f32_to_i8_test-linux",
  "pebble-pebble-ctest-quant_i32_to_i8_test-linux",
  "pebble-pebble-mlirtest-ball_quant_f32_to_i8-linux",
  "pebble-pebble-mlirtest-bank_quant_f32_to_i8-linux",
  "pebble-pebble-mlirtest-ball_quant_i32_to_i8-linux",
  "pebble-pebble-mlirtest-bank_quant_i32_to_i8-linux",
  "pebble-pebble-ctest-im2col_window_test-linux",
  "pebble-pebble-mlirtest-ball_im2col_6x6_k3-linux",
  "pebble-pebble-mlirtest-bank_im2col_6x6_k3-linux",
  "pebble-pebble-ctest-int2fp_tensor_values_test-linux",
  "pebble-pebble-ctest-int2fp_tensor_groups_test-linux",
  "pebble-pebble-ctest-int2fp_tensor_rows_test-linux",
  "pebble-pebble-ctest-int2fp_channel_lanes_test-linux",
  "pebble-pebble-ctest-int2fp_channel_base_test-linux",
  "pebble-pebble-ctest-int2fp_channel_two_rows_test-linux",
  "pebble-pebble-mlirtest-ball_int2fp_4x4-linux",
  "pebble-pebble-mlirtest-bank_int2fp_4x4-linux",
  "pebble-pebble-mlirtest-ball_int2fp_relu_4x4-linux",
  "pebble-pebble-mlirtest-bank_int2fp_relu_4x4-linux",
  "pebble-pebble-ctest-mega_conv_pipeline_test-linux",
  "pebble-pebble-mlirtest-tile_mega_matmul-linux",
  "pebble-pebble-mlirtest-tile_mega_conv2d-linux",
]
