[workloads]
search_path = "workloads/src"
tests = [
  "pebble-pebble-ctest-mvin_mvout_test-baremetal",
  "pebble-pebble-ctest-mvin_mvout_stride_test-baremetal",
  "pebble-pebble-mlirtest-base_mvin_mvout_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-base_bank_mvin_mvout_16x16_i8-baremetal",
  "pebble-pebble-ctest-transpose_i8_16x16_test-baremetal",
  "pebble-pebble-ctest-transpose_i8_16x32_test-baremetal",
  "pebble-pebble-ctest-transpose_i32_8x16_test-baremetal",
  "pebble-pebble-mlirtest-ball_transpose_16x16_i8-baremetal",
  "pebble-pebble-mlirtest-bank_transpose_16x16_i8-baremetal",
  "pebble-pebble-ctest-smatmul_bias_accumulate_test-baremetal",
  "pebble-pebble-ctest-smatmul_single_block_test-baremetal",
  "pebble-pebble-mlirtest-ball_smatmul_bias_accumulate-baremetal",
  "pebble-pebble-mlirtest-bank_smatmul_bias_accumulate-baremetal",
  "pebble-pebble-ctest-quant_f32_to_i8_test-baremetal",
  "pebble-pebble-ctest-quant_i32_to_i8_test-baremetal",
  "pebble-pebble-mlirtest-ball_quant_f32_to_i8-baremetal",
  "pebble-pebble-mlirtest-bank_quant_f32_to_i8-baremetal",
  "pebble-pebble-mlirtest-ball_quant_i32_to_i8-baremetal",
  "pebble-pebble-mlirtest-bank_quant_i32_to_i8-baremetal",
  "pebble-pebble-ctest-im2col_window_test-baremetal",
  "pebble-pebble-mlirtest-ball_im2col_6x6_k3-baremetal",
  "pebble-pebble-mlirtest-bank_im2col_6x6_k3-baremetal",
  "pebble-pebble-ctest-int2fp_tensor_values_test-baremetal",
  "pebble-pebble-ctest-int2fp_tensor_groups_test-baremetal",
  "pebble-pebble-ctest-int2fp_tensor_rows_test-baremetal",
  "pebble-pebble-ctest-int2fp_channel_lanes_test-baremetal",
  "pebble-pebble-ctest-int2fp_channel_base_test-baremetal",
  "pebble-pebble-ctest-int2fp_channel_two_rows_test-baremetal",
  "pebble-pebble-mlirtest-ball_int2fp_4x4-baremetal",
  "pebble-pebble-mlirtest-bank_int2fp_4x4-baremetal",
  "pebble-pebble-mlirtest-ball_int2fp_relu_4x4-baremetal",
  "pebble-pebble-mlirtest-bank_int2fp_relu_4x4-baremetal",
  "pebble-pebble-ctest-mega_conv_pipeline_test-baremetal",
  "pebble-pebble-ctest-int8mul_test-baremetal",
  "pebble-pebble-mlirtest-tile_mega_matmul-baremetal",
  "pebble-pebble-mlirtest-tile_mega_conv2d-baremetal",
]
